# -*- coding: utf-8 -*-
"""Best Time to Buy and Sell Stock

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13p1-_5XL1kJXO3LJwwVqPNZOOh5tY2vl
"""

class Solution(object):
    def maxProfit(self, prices):
        """
        :type prices: List[int]
        :rtype: int
        beats 59.75% in runtime and 47.05% in memory usage, runtime is O(n) and memory use is O(1)
        """
        maxProfit = 0
        i = 0
        j = 1
        while j < len(prices):
            #the below line is because of the fact that if you have a later day that is cheaper than the current, then you should NOT buy at the current day
            if prices[i] >= prices[j]:
                i = j
            elif prices[j] - prices[i] > maxProfit:
                maxProfit = prices[j] - prices[i]
            j += 1
        return maxProfit


#SECOND ATTEMPT
class Solution(object):
    def maxProfit(self, prices):
        """
        :type prices: List[int]
        :rtype: int
        """
        maxProfit = 0
        i = 0
        j = 1
        while j < len(prices):
            if prices[i] >= prices[j]:
                i = j
            profit = prices[j] - prices[i]
            maxProfit = profit if maxProfit < profit else maxProfit
            j += 1
        return maxProfit

        
        
